name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-linting-and-code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml
        tools: php-cs-fixer, phpstan

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Check PHP syntax
      run: find . -type f -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

    - name: PHP CodeSniffer
      run: ./vendor/bin/phpcs --standard=PSR12 src/

    - name: PHPStan
      run: ./vendor/bin/phpstan analyse src/ --level=max || true

    - name: PHPUnit tests
      run: composer test